# id: 1
server:
  address: "server:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 135
  # La linea mas larga de los CSV es de 59 caracteres = 59 bytes.
  # Si hago 8kb = 8000 bytes // 59 bytes me da 135 maximos batches para no pasarme de 8kb.
  # Esto tambien me deja lugar para el overhead del protocolo.